version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: 'celery -A app.app worker -l INFO -B'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/space_x
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: 'celery -A app.app flower'
    ports:
      - 5555:5555
    depends_on:
      - worker
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=space_x
    ports:
      - '5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379'
volumes:
  db:
    driver: local